---
title: Plot alignment scores
author: Shaun Jackman
output:
  html_document:
    keep_md: true
params:
  input_tsv:
    label: "Input TSV file of read alignments with AS column"
    value: "pglauca.psitchensis.longranger.align.bam.bx.tsv"
    input: select
    choices: [
        "organelles.psitchensis.longranger.bam.bx.tsv",
        "organelles.psitchensis.proper.bam.as.tsv",
        "pglauca.psitchensis.longranger.align.bam.bx.tsv",
        "pglauca.psitchensis.proper.bam.as.tsv",
        "psitchensismt.1.psitchensis.bx.bam.bx.tsv"]
---

```{r setup}
knit_print.data.frame <- function(x, ...) kable(x) %>% paste(collapse = "\n") %>% asis_output
input_tsv <- params$input_tsv
```

# Load packages
```{r load-packages}
library(dplyr)
library(ggplot2)
library(magrittr)
library(readr)
```

# Read data
```{r read-data}
data_orig <- read_tsv(input_tsv)
data_all <- data_orig %>% transform(Proper = bitwAnd(Flags, 2) != 0)
data_proper <- data_all %>% filter(Proper)
```

# Descriptive stats
```{r stats}
min_as <- 40
data_good <- data_all %>% filter(AS >= min_as)
data_all %$% c(length(AS), fivenum(AS))
data_good %$% c(length(AS), fivenum(AS))
nrow(data_good) / nrow(data_all)
```

# Boxplot of all alignment scores
```{r as-boxplot-all}
ggplot(data_all) + aes(x = "All", y = AS) + geom_boxplot(coef = 9) + ylim(0, NA)
```

# Boxplot of proper alignment scores
```{r as-boxplot-proper}
ggplot(data_all) + aes(x = Proper, y = AS) + geom_boxplot() + ylim(0, NA)
```

# Boxplot of good alignment scores
```{r as-boxplot-good}
ggplot(data_good) + aes(x = "Good", y = AS) + geom_boxplot() + ylim(0, NA)
```

# Boxplot of good and proper alignment scores
```{r as-boxplot-good-proper}
ggplot(data_good) + aes(x = Proper, y = AS) + geom_boxplot() + ylim(0, NA)
```

# Histogram of all alignment scores
```{r as-histogram-all}
ggplot(data_all) + aes(x = AS) + geom_histogram(binwidth = 1)
ggplot(data_all) + aes(x = AS) + geom_histogram(binwidth = 20, center = 10)
```

# Histogram of proper alignment scores
```{r as-histogram-proper}
ggplot(data_proper) + aes(x = AS) + geom_histogram(binwidth = 1)
ggplot(data_proper) + aes(x = AS) + geom_histogram(binwidth = 20, center = 10)
```

# Histogram of good alignment scores
```{r as-histogram-good}
ggplot(data_good) + aes(x = AS) + geom_histogram(binwidth = 1)
ggplot(data_good) + aes(x = AS) + geom_histogram(binwidth = 20, center = 10)
```
