---
title: Break scaffolds at loci not supported by molecules
author: Shaun Jackman
output:
  html_document:
    keep_md: true
params:
  input_tsv:
    label: "Input TSV file of misassemblies"
    value: "draft.path.breakpoints.tsv"
    input: text
  input_fai:
    label: "Input FAI file of scaffold sizes"
    value: "draft.path.fa.fai"
    input: text
  output_bed:
    label: "Output BED file of breaktig coordinates"
    value: "draft.path.breakpoints.tigs.bed"
    input: text
---

```{r setup}
library(dplyr)
library(knitr)
library(magrittr)
library(readr)
library(ggplot2)
library(scales)
library(tidyr)
library(uniqtag)

knit_print.data.frame <- function(x, ...) kable(x) %>% paste(collapse = "\n") %>% asis_output
misassemblies_filename <- params$input_tsv
fai_filename <- params$input_fai
output_bed_filename <- params$output_bed
```

# Read the data
```{r read-data}
misassemblies_orig <- read_tsv(misassemblies_filename,
	col_types = cols(Rname = col_character(), Pos = col_integer()))
misassemblies <- misassemblies_orig %>% select(Rname, Pos)

fai <- read_tsv(fai_filename, col_names = c("Rname", "Pos"), col_types = "ci---")
```

# Determine coordinates of subsequences
```{r transform}
size_threshold <- 200

bed <- rbind(
		mutate(misassemblies, Pos = Pos - 1L),
		mutate(fai, Pos = 0L),
		fai) %>%
	mutate(Rname_int = as.integer(sub("[^0-9].*$", "", Rname))) %>%
	arrange(!is.na(Rname_int), Rname_int, Rname, Pos) %>%
	transmute(Rname, Start = Pos, End = lead(Pos)) %>%
	drop_na() %>%
	filter(End - Start >= size_threshold) %>%
	mutate(Name = make_unique(Rname))
```

# Write the BED file to disk
```{r write-results}
bed %>% write_tsv(output_bed_filename, col_names = FALSE)
```

# Coordinates of subsequences
```{r table}
bed
```
