---
title: Determine enrichment of barcode overlap
author: Shaun Jackman
output:
  html_document:
    keep_md: true
---

```{r setup}
library(dplyr)
library(ggplot2)
library(purrr)
library(readr)
library(rPref)
library(tidyr)
```

# Read data
```{r read-data}
counts <- read_tsv("tmp/psitchensiscpmt_3.psitchensis.bx.c1_e5000_r0.220000.arcs.tsv") %>%
	mutate(cp = grepl("KU", U) | grepl("KU", V))
```

# Determine enrichment of barcode overlap
```{r transform-data}
p_values <- counts %>%
	rowwise() %>%
	mutate(p = phyper(Count_shared - 1, Count_U, Count_all - Count_U, Count_V, lower.tail = FALSE)) %>%
	ungroup() %>%
	mutate(q = p.adjust(p, "BH"))
top_n(p_values, 10, desc(p))
p_values %>% filter(U == "131-", V == "KU215903-")
p_values %>% filter(p < 0.05) %>% nrow()
p_values %>% filter(q < 0.05) %>% nrow()

3043*16754/21
phyper(21 - 1, 3043, 169948 - 3043, 16754, lower.tail = FALSE)
phyper(21 - 1, 3043, 2427734 - 3043, 16754, lower.tail = FALSE)
phyper(21 - 1, 3043, 1504171 - 3043, 16754, lower.tail = FALSE)
```

# Plot p-values
```{r stripplot-p}
ggplot(p_values) + aes(x = p) + geom_histogram(binwidth = 0.01, boundary = 0)
ggplot(p_values) + aes(x = q) + geom_histogram(binwidth = 0.01, boundary = 0)
ggplot(p_values) + aes(x = p, y = q) + geom_point()
ggplot(p_values) + aes(x = p, y = q) + geom_point() + coord_cartesian(c(0, 0.05))
```

# Scatter plot FPR vs number of shared barcodes
```{r plot-fpr-shared}
plot <- ggplot(p_values) +
	aes(x = Count_shared, y = p) +
	geom_point(size = 1, alpha = 0.1)
plot
plot + coord_cartesian(xlim = c(1, 20), ylim = c(0, 0.5))
ggplot(p_values) + aes(x = factor(Count_shared), y = p) + stat_boxplot() + coord_cartesian(xlim = c(1, 20))
```

# Estimate number of false positives and true positives
```{r fpr}
fpr <- list(0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1) %>% map_df(
	function(x) p_values %>% filter(q < x) %>% summarise(
		FPR = x,
		max_q = max(q),
		n = n(),
		FP = ceiling(n() * max(q)),
		TP = n - FP,
		max_p = max(p),
		min_shared = min(Count_shared)))
fpr
```

# Plot FPR
```{r plot-fpr}
ggplot(fpr %>%
		filter(FPR < 0.5) %>%
		gather(key = TP_FP, value = Count, TP, FP) %>%
		mutate(FPR = factor(FPR))) +
	aes(x = FPR, y = Count, fill = TP_FP, group = TP_FP) +
	geom_col() +
	scale_y_continuous(breaks = function(x) seq(0, x[2], 100))
```

# Histogram of number of shared barcodes
```{r plot-shared}
ggplot(p_values) +
	aes(x = Count_shared, group = q < 0.05, fill = q < 0.05) +
	geom_histogram(binwidth = 5, boundary = 0) +
	coord_cartesian(ylim = c(0, 200))
```

# Inspect plastid
```{r plastid}
p_values %>% filter(cp) %>% nrow()
p_values %>% filter(cp, Count_shared >= 5) %>% nrow()
p_values %>% filter(cp, Count_shared >= 10) %>% nrow()
p_values %>% filter(cp, Count_shared >= 20) %>% nrow()
p_values %>% filter(cp, Count_shared >= 30) %>% nrow()

p_values %>% filter(cp, q < 0.05)
p_values %>% filter(cp, q < 0.02)

p_values %>% filter(cp, q < 0.05, Count_shared >= 10)
```

# Scatter plot of FPR and shared barcodes
```{r scatter-fpr-shared}
ggplot(p_values) +
	aes(x = Count_shared, y = q, colour = cp) +
	geom_point() +
	coord_cartesian(c(0, 25))
```

# Pareto frontier of plastid FPR and shared barcodes
```{r plastid-pareto}
cp_pareto <- p_values %>% filter(cp) %>%
	psel(low(q) * high(Count_shared), top = nrow(p_values)) %>%
	rename(Pareto = .level)

ggplot(cp_pareto) +
	aes(x = Count_shared, y = q) +
	geom_point() +
	geom_step(data = filter(cp_pareto, Pareto == 1), direction = "vh")
```

# Write data
```{r write-data}
p_values %>% write_tsv("tmp/psitchensiscpmt_3.psitchensis.bx.c1_e5000_r0.220000.arcs.p.tsv")
```
